# Generated by Django 4.2.11 on 2024-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
