# Generated by Django 4.2.11 on 2024-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_children_date_of_birth_item_children_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
