# Generated by Django 4.2.11 on 2024-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
